### ISSUE TITLE
Improve info_url

### ISSUE THREAD

**Issue by equivalentideas** [planningalerts-scrapers/port_macquarie_hastings#1]
Currently the info_url collected is a generic page for searching for DAs: https://eservice.hastings.nsw.gov.au/eservice/dialog/daEnquiryInit.do?doc_typ=(10,15)&nodeNum=115765 , see the code here https://github.com/planningalerts-scrapers/port_macquarie_hastings/blob/master/scraper.php#L101 .

While this is useful to people in that they can then look up and find the application they're looking for (nice one @LoveMyData :+1: ), it would be better to help people as much as possible by taking them to some information relating to the development they are interested in.

Unfortunately it doesn't seem possible to link to an actual application, which would be best. We could however do a search for an application, using the application number, by customising the query string or entering a search. This at least provides some information specific to the actual DA the user is looking for: https://eservice.hastings.nsw.gov.au/eservice/dialog/daEnquiry.do?number=%09+819%2F2015

What do you think @LoveMyData ?

**Comment by LoveMyData** [comment]
Not possible from what I can see, try to open it in incognito mode and see the errors.

**Comment by LoveMyData** [comment]
Council system is now completed changed.... Closing this ticket as it is no longer related
