### ISSUE TITLE
Addresses are sometimes incorrectly geocoded

### ISSUE THREAD

**Issue by henare** [planningalerts-scrapers/port_macquarie_hastings#5]
This one is showing up in Newtown: https://www.planningalerts.org.au/applications/801444

We got an email from someone saying they were getting "regular alerts" that were wrong. Is this more widespread than just this hiccup?

**Comment by LoveMyData** [comment]
The scraper doesn't involve with geocode, it is whatever the backend PA use to geocode fetched an incorrect lng/lat.
Address collected is correct as per council's DA - '23 Sunrise Pl, King Creek 2446 NSW'
